services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: mayss
      POSTGRES_PASSWORD: mayss
      POSTGRES_DB: mayss
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mayss"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg2://mayss:mayss@db:5432/mayss
      SECRET_KEY: dev-secret-change-me
      PUBLIC_BASE_URL: https://mayersscott.ru
    ports:
      - "8001:8000"
    # В продакшене лучше убрать volumes для кода бэкенда, 
    # чтобы контейнер использовал код, который вшит в него при сборке.
    # volumes:
    #   - ./backend:/app 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: sh entrypoint.sh

  frontend:
    image: nginx:alpine

    ports:
      - "8081:80"

    volumes:
      - ./frontend:/usr/share/nginx/html:ro

    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.4.1

    ports:
      - "3001:3000"

    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_DISABLE_LOGIN_FORM=true

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: