apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    user: mayss
    secureJsonData:
      password: mayss
    jsonData:
      database: mayss
      sslmode: disable
      postgresVersion: 16
    isDefault: true
